
services:
  chamados-ti:
    container_name: chamadosti-app
    build: .
    ports:
      - "${CHAMADOSTI_PORT}:8000"
    depends_on:
      - redis-chamadosti
    restart: always
    env_file:
      - .env
    networks:
      - network-chamadosti
    
  selenium-chamadosti:
      container_name: selenium-chamadosti
      image: selenium/standalone-chrome:latest
      restart: always
      ports:
        - "4444:4444"
      volumes:
        - /dev/shm:/dev/shm
      networks:
        - network-chamadosti
  worker-chamadosti:
    build: .
    command: celery -A app worker --loglevel=info
    restart: always
    env_file:
      - .env
    depends_on:
      - redis-chamadosti
    networks:
      - network-chamadosti

  flower:
    container_name: flower-chamadosti
    build: .
    command: celery -A app flower --port=5555
    restart: always
    ports:
      - "5555:5555"
    env_file:
      - .env  
    depends_on:
      - redis-chamadosti
    networks:
      - network-chamadosti

  redis-chamadosti:
    container_name: redis-chamadosti
    image: redis:latest
    restart: always
    networks:
      - network-chamadosti

networks:
  network-chamadosti:
    driver: bridge
