version: '3'

services:
  app-chamados:
    build: .
    command: python manage.py runserver 0.0.0.0:${DJANGO_PORT}  
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    depends_on:
      - redis-app-chamados
    networks:
      - network-chamadosti
    restart: always
    env_file:
      - .env  
    volumes:
      - .:/django-project
      - ./db.sqlite3:/django-project/db.sqlite3  # Monta o banco de dados
  selenium-app-chamados:
      image: selenium/standalone-chrome:latest
      restart: always
      volumes:
        - /dev/shm:/dev/shm
      networks:
        - network-chamadosti
  worker-app-chamados:
    build: .
    command: celery -A app worker --loglevel=info
    restart: always
    volumes:
      - .:/django-project
      - ./db.sqlite3:/django-project/db.sqlite3  # Monta o banco de dados
    depends_on:
      - redis-app-chamados
    networks:
      - network-chamadosti
    env_file:
      - .env  

  flower-app-chamados:
    build: .
    command: celery -A app flower --port=5555 --db=sqlite:///flower.db
    restart: always
    ports:
      - "5555:5555"
    depends_on:
      - redis-app-chamados
    networks:
      - network-chamadosti
    env_file:
      - .env  
    volumes:
      - .:/django-project
      - ./db.sqlite3:/django-project/db.sqlite3  # Monta o banco de dados

  redis-app-chamados:
    image: redis:latest
    restart: always
    networks:
      - network-chamadosti

networks:
  network-chamadosti:
    driver: bridge
