version: '3'

services:
  chamados-ti:
    container_name: chamadosti-app
    build: .
    command: python manage.py runserver 0.0.0.0:8000  
    ports:
      - "${CHAMADOS_TI}:8000"
    depends_on:
      - redis-chamadosti
    restart: always
    env_file:
      - .env  
    volumes:
      - .:/django-project
      - ./db.sqlite3:/django-project/db.sqlite3  # Monta o banco de dados
    networks:
      - network-chamadosti

  selenium-chamadosti:
      container_name: selenium-chamadosti
      image: selenium/standalone-chrome:latest
      restart: always
      volumes:
        - /dev/shm:/dev/shm
      networks:
        - network-chamadosti
  worker-app-chamados:
    build: .
    command: celery -A app worker --loglevel=info
    restart: always
    volumes:
      - .:/django-project
      - ./db.sqlite3:/django-project/db.sqlite3  # Monta o banco de dados
    env_file:
      - .env
    depends_on:
      - redis-chamadosti
    networks:
      - network-chamadosti

  flower:
    container_name: flower-chamadosti
    build: .
    command: celery -A app flower --port=5555 --db=sqlite:///flower.db
    restart: always
    ports:
      - "5555:5555"
    env_file:
      - .env  
    volumes:
      - .:/django-project
      - ./db.sqlite3:/django-project/db.sqlite3  # Monta o banco de dados
    depends_on:
      - redis-chamadosti
    networks:
      - network-chamadosti

  redis-chamadosti:
    container_name: redis-chamadosti
    image: redis:latest
    restart: always
    networks:
      - network-chamadosti

networks:
  network-chamadosti:
    driver: bridge
  
